MyUser/urls.py
from django.urls import path

from .views import logout

app_name = "MyUser"

urlpatterns = [
	path('logout', logout, name='logout'),
]

project/urls.py
from django.urls import path, include

from MyUser.views import login, signup
from .admin import admin_site
from .views import index, base_dashboard

urlpatterns = [
    path('admin/', admin_site.urls),
    path('login/', login, name='login'),
    path('signup/', signup, name='signup'),
    path('', index, name='index'),
    path('in/', base_dashboard, name='base_dashboard'),
    path('user/', include('MyUser.urls')),
]

MyUser/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

from .managers import MyUserManager

class MyUser(AbstractUser):

	USERNAME_FIELD = "email"
	REQUIRED_FIELDS = ['password']

	email = models.EmailField(_('email address'), unique=True)
	username = models.CharField(max_length=255, null=True, blank=True, unique=False)

	objects = MyUserManager()

	class Meta:
		app_label = "MyUser"

	def __str__(self):
		return self.first_name + " " + self.last_name

MyUser/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

class SignUpForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
	
	class Meta:
		model = get_user_model()
		fields = ('email', 'password')

MyUser/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.urls import reverse

from .forms import SignUpForm

@login_required(login_url='/login')
def logout(request):
	auth.logout(request)
	return redirect("index")

def login(request):
	context = {'login_failed': False}
	if request.POST:
		email = request.POST['email']
		password = request.POST['password']
		user = auth.authenticate(request, email=email, password=password)
		if user:
			auth.login(request, user)
			return redirect("base_dashboard")
		else:
			context['login_failed'] = True
	return render(request, "public/login.html", context)

def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			email = form.cleaned_data.get('email')
			raw_password = form.cleaned_data.get('password1')
			user = auth.authenticate(email=email, password=raw_password)
			auth.login(request, user)
			return redirect("base_dashboard")
	else:
		form = SignUpForm()
	return render(request, "public/signup.html", {'form': form})

project/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

def index(request):
	return redirect('login')

@login_required(login_url='/login')
def base_dashboard(request):
	return render(request, "dashboard.html", context={'user': request.user})

frontend/templates/base.html
{% load static %}

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>ProjectBudget</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'admin-lte/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/skins/skin-green.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  <!-- DataTables -->
  <link rel="stylesheet" type="text/css" href="{% static 'admin-lte/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">

  <!-- ProjectBudget css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/projectbudget.css' %}">

  {% block css_extras %}{% endblock %}
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-green {% block body_class %}{% endblock %}">

{% block content %}{% endblock %}

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{% static 'admin-lte/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'admin-lte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<!-- DataTables -->
<script src="{% static 'admin-lte/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'admin-lte/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>

{% block js_extras %}{% endblock %}

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>

frontend/templates/base_dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block body_class %}sidebar-mini{% endblock %}

{% block content %}
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">P<b>B</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Project<b>Budget</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{% static 'img/avatar.png' %}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{ user }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'img/avatar.png' %}" class="img-circle" alt="User Image">

                <p>
                  {{ user }}
                </p>
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'MyUser:logout' %}" class="btn btn-default btn-flat">Logout</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'img/avatar.png' %}" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>{{ user }}</p>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MENU</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active"><a href="#"><i class="fa fa-line-chart"></i> <span>Dashboard</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      {% block content_header %}{% endblock %}
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

      {% block page_content %}{% endblock %}

      <!--------------------------
        | Your Page Content Here |
        -------------------------->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- Default to the left -->
    Created by <a href="http://areeba.ca">Areeba Aziz</a>
  </footer>
</div>
<!-- ./wrapper -->
{% endblock %}

frontend/templates/dashboard.html
{% extends 'base_dashboard.html' %}
{% load static %}

{% block content_header %}
<h1>
	Dashboard
</h1>
<ol class="breadcrumb">
	<li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
</ol>
{% endblock %}

{% block page_content %}

<div class="row">
	<!-- Overview Boxes -->
	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-green">
				<i class="fa fa-money"></i>
			</span>
			<div class="info-box-content">
				<span class="info-box-text">Net Total</span>
				<span class="info-box-number">$100.00</span>
			</div>
		</div>
	</div>

	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-yellow">
				<i class="fa fa-database"></i>
			</span>
			<div class="info-box-content">
				<span class="info-box-text">Net Cash</span>
				<span class="info-box-number">$100.00</span>
			</div>
		</div>
	</div>

	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-blue">
				<i class="fa fa-area-chart"></i>
			</span>
			<div class="info-box-content">
				<span class="info-box-text">Net Investments</span>
				<span class="info-box-number">$70.00</span>
			</div>
		</div>
	</div>

	<div class="col-md-3 col-sm-6 col-xs-12">
		<div class="info-box">
			<span class="info-box-icon bg-red">
				<i class="fa fa-bank"></i>
			</span>
			<div class="info-box-content">
				<span class="info-box-text">Total Debt</span>
				<span class="info-box-number">$100.00</span>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<!-- My Accounts -->
	<div class="col-md-6 col-sm-12 col-xs-12">
		<div class="box box-solid box-primary">
			<div class="box-header">
				<h3 class="box-title">My Accounts</h3>
			</div>
			<div class="box-body ">
				<table id="table_myaccounts" class="table table-hover">
					<thead>
						<tr>
							<th>Name</th>
							<th>Type</th>
							<th>Amount</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>TD Checking</td>
							<td>Cash</td>
							<td>$200</td>
						</tr>
						<tr>
							<td>TD Everyday Savings</td>
							<td>Cash</td>
							<td>$500</td>
						</tr>
						<tr>
							<td>Wealthsimple Trade</td>
							<td>Investment</td>
							<td>$400</td>
						</tr>
						<tr>
							<td>NSLSC Loan</td>
							<td>Debt</td>
							<td>-$1000</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	
	<!-- Upcoming Transfers -->
	<div class="col-md-6 col-sm-12 col-xs-12">
		<div class="box box-solid box-warning">
			<div class="box-header">
				<h3 class="box-title">Upcoming Transfers</h3>
			</div>
			<div class="box-body ">
				<table id="table_upcomingtransfers" class="table table-hover">
					<thead>
						<tr>
							<th>From</th>
							<th>To</th>
							<th>Amount</th>
							<th>Date</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>TD Chequing</td>
							<td>WealthSimple Trade</td>
							<td>$50</td>
							<td>May 10, 2020</td>
						</tr>
						<tr>
							<td>Salary - Amazon</td>
							<td>TD Chequing</td>
							<td>$2000</td>
							<td>May 15, 2020</td>
						</tr>
						<tr>
							<td>TD Chequing</td>
							<td>Landlord for Rent</td>
							<td>$500</td>
							<td>June 1, 2020</td>
						</tr>
						<tr>
							<td>TD Credit</td>
							<td>Spotify</td>
							<td>$4.90</td>
							<td>June 4, 2020</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<!-- Projections --> 
<div class="row">
	<div class="col-md-12">
		<div class="box box-solid box-success">
			<div class="box-header">
				<h3 class="box-title">Future Projections</h3>
			</div>
			<div class="box-body">
				<canvas id="projectionsCanvas"></canvas>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block js_extras %}
<script type="text/javascript">
	$(document).ready(function() {
	    $('#table_myaccounts').DataTable({
	    	'paging': false,
	    	'searching': false,
	    	'info': false
	    });
	} );

	$(document).ready(function() {
	    $('#table_upcomingtransfers').DataTable({
	    	'paging': false,
	    	'searching': false,
	    	'info': false
	    });
	} );
</script>
<script src="{% static 'chart.js/dist/Chart.bundle.min.js' %}"></script>
<script type="text/javascript">
	var transferData = [
		12, 0, 0, 5, 2, 3,
		0, -5, 0, 4, 2, -3,
		11, 8, 3, -9, -7, 0,
		14, 0, 0, -4, 3, 1,
	]
	const colours = transferData.map((value) => value < 0 ? '#dd4b39' : '#00a65a');
	var ctx = document.getElementById('projectionsCanvas');
	var myChart = new Chart(ctx, {
	    type: 'bar',
	    data: {
	        labels: [
	        	'20/05/03', '20/05/04', '20/05/05', '20/05/06', '20/05/07', '20/05/08',
	        	'20/05/09', '20/05/10', '20/05/11', '20/05/12', '20/05/13', '20/05/14',
	        	'20/05/15', '20/05/16', '20/05/17', '20/05/18', '20/05/19', '20/05/20',
	        	'20/05/21', '20/05/22', '20/05/23', '20/05/24', '20/05/25', '20/05/26'
	        ],
	        datasets: [{
	            label: 'Transfers',
	            data: transferData,
	            borderWidth: 1,
	            backgroundColor: colours,
	        }, {
	        	label: 'Net Total',
	        	data: [
	            	12, 12, 12, 17, 19, 22,
	            	22, 17, 17, 21, 23, 20,
	            	31, 39, 42, 33, 26, 26,
	            	40, 40, 40, 36, 39, 40,	
	        	],
	        	type: 'line',
	        	backgroundColor: "#3c8dbc",
	        }]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero: true
	                },
	                scaleLabel: {
	                	display: true,
	                	labelString: 'Amount ($)',
	            	}
	            }],
	            xAxes: [{
	            	scaleLabel: {
	            	display: true,
	            	labelString: 'Date',
	            	}
	            }
	            ]
	        },
	        legend: {
	        	display: true,

	        }
	    }
	});
</script>
{% endblock %}